#! /bin/sh

/bin/mount -a

for initscript in /etc/init.d/S[0-9][0-9]*
do
	if [ -x $initscript ] ;
	then
		echo "[RCS]: $initscript"
		$initscript
	fi
done

#get /dev/mtdblockN with mtd name
getmtd() 
{
	MTDNAME=$1
	temp=`grep $MTDNAME /proc/mtd`
	temp=${temp%%:*}
	echo ${temp/mtd/\/dev\/mtdblock}
}

#mtd1: 00480000 00010000 "appfs"
APPFS_MTD=`getmtd \"appfs\"`
echo $APPFS_MTD

mkdir /tmp/appfs
mount -t squashfs $APPFS_MTD /tmp/appfs
mkdir /progs -p
mkdir /home -p
mount /tmp/appfs/progs /progs/
mount /tmp/appfs/home /home

/home/bashrc.sh
